id: IA999460F
legacy_id: P004596
ocr_import_info:
  bdrc_scan_id: W1PD76384
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T20:31:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:55:57.760599+00:00'
last_modified: 2022-09-01 12:56:02.149967
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD76384
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD76384
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རི་ཁྲོད་བཀྲ་ཤིས་ཆོས་སྡིངས་ཀྱི་གདན་རབས།
  author: གཅན་ཚ་བློ་བཟང་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.8204858022086289
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I1KG21575:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG21575
      total_pages: 20
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG21575.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8204858022086289
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
