id: P004596
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 11:43:32.417289
source_metadata:
  id: bdr:W1PD76384
  title: རི་ཁྲོད་བཀྲ་ཤིས་ཆོས་སྡིངས་ཀྱི་གདན་རབས།
  author: ''
  volumes:
    34de1eb8e3be456184b36d6bdb1a4f8d:
      image_group_id: I1KG21575
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
