id: P004596
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD76384
  title: རི་ཁྲོད་བཀྲ་ཤིས་ཆོས་སྡིངས་ཀྱི་གདན་རབས།
  author: ''
  volumes:
    34de1eb8e3be456184b36d6bdb1a4f8d:
      image_group_id: I1KG21575
      title: ''
      volume_number: 1
      total_pages: 20
      base_file: v001.txt
